package lk.ijse.cosmeticshop.util;

/*
    @author BUDDINI
    @created 11/24/2022 - 7:12 PM   
*/

public enum Routes {
    HOME,LOGIN,ADMIN_DASHBOARD,OWNER_DASHBOARD,CUSTOMER,PRODUCT,PRODUCT_ADMIN,DELIVERY,EMPLOYEE,INCOME_REPORT,ORDER,SUPPLIER,PLACE_ORDER,PLACE_ORDER_NEW

}
